Feature/5
GDG-SWU/2023-server-toy-project-team-b pull request #10
Opened 2023-11-13 11:18 UTC by nanna29

2023-11-14 17:11 UTC, nusuy requested changes
고생하셨어요!
코멘트 확인하시고 수정 커밋 부탁드려요🙌

2023-11-14 17:11 UTC, nusuy commented on server-toy-project/src/main/java/com/gdsc_teamb/servertoyproject/domain/repository/BoardRepository.java
> +public interface BoardRepository extends JpaRepository<PostEntity, Long> {
리포지토리명은 `Entity명+Repository`로 설정해주는 것이 컨벤션입니다!
해당 Repository는 `PostEntity`에 대한 Repository이므로 `PostRepository`로 변경해주세요.

2023-11-14 17:11 UTC, nusuy commented on server-toy-project/src/main/java/com/gdsc_teamb/servertoyproject/domain/repository/BoardRepository.java
> +    List<PostEntity> findAllDesc();
작성하신 것처럼 직접 쿼리문을 작성해서 데이터를 조회할 수도 있지만, JPA에서 메소드로 쿼리문을 구현할 수 있도록 제공하고 있기 때문에 먼저 메소드로 구현해보시고, 더 복잡한(메소드로 구현이 안 되는) 쿼리가 필요하다면 그때 직접 쿼리를 작성하는 방식으로 개발하시는 것이 좋습니다.
이 쿼리는 메소드로 구현 가능하기 때문에 명명 규칙에 맞추어 변경하시면 좋을 것 같아요!

아래 링크는 메소드 명명 규칙에 대한 레퍼런스입니다. 참고하셔서 수정해주세요!
https://blog.jiniworld.me/128

2023-11-14 17:11 UTC, nusuy commented on server-toy-project/src/test/java/com/gdsc_teamb/servertoyproject/controller/BoardControllerTest.java
> +    public void Posts_등록() throws Exception{
스터디 교재에서 테스트 메소드명을 한글로 적었기 때문에 그 방식이 더 익숙하실텐데, 메소드명은 영어로 작성하는 것이 좋습니다! `@DisplayName`으로 테스트 이름을 설정하실 수 있고 테스트 결과창에서도 해당 이름으로 확인하실 수 있어요.
따라서 기존 메소드명은 영어로 수정하시고 `@DisplayName`으로 테스트명 설정하시면 좋을 것 같습니다! (다른 테스트들도 변경 부탁드려요)

2023-11-14 17:11 UTC, nusuy commented on server-toy-project/src/test/java/com/gdsc_teamb/servertoyproject/controller/BoardControllerTest.java
> +        assertThat(responseEntity.getBody()).isGreaterThan(0L);
Http 요청으로 API 테스트 하신 것 정말 좋습니다👍
다만, 스프링에서 제공하는 `MockMvc`으로 Http 요청 테스트를 구현하는 방식도 있으니 관련 내용도 참고하시면 좋을 것 같습니다!

2023-11-14 17:11 UTC, nusuy commented on server-toy-project/src/main/java/com/gdsc_teamb/servertoyproject/service/BoardService.java
> +                orElseThrow(()->new IllegalArgumentException("해당 게시글이 없습니다. id="+id));
데이터 조회 후 `orElseThrow()`로 예외 처리하신 부분은 정말 좋아요!
하지만, 해당 Exception이 던져지면 서버 측에서는 확인할 수 있지만, API 사용자는 요청에 실패한 이유를 파악하기 어렵습니다. 에러 원인을 http 응답으로 전달하는 부분을 추가하시면 좋을 것 같습니다!
(다른 Exception 처리 부분들도 다시 확인 부탁드려요)

2023-11-14 17:11 UTC, nusuy commented on server-toy-project/src/test/java/com/gdsc_teamb/servertoyproject/controller/BoardControllerTest.java
> +        userRepository.deleteAll();
테스트 종료 후 테스트 데이터들을 없애는 로직을 넣으신 것은 너무 좋아요!
하지만 이렇게 구현한 경우 테스트 DB와 실제 프로덕션 DB가 분리되어 있지 않다면, 실제 데이터까지 삭제되기 때문에 위험합니다.
테스트 클래스에 `@Transactional`을 넣으면 해당 클래스에서 작업한 데이터가 롤백되므로 해당 코드 대신 사용하셔도 좋을 것 같습니다.

2023-11-14 17:11 UTC, nusuy commented on server-toy-project/src/test/java/com/gdsc_teamb/servertoyproject/controller/BoardControllerTest.java
> +        assertThat(all.get(0).getContent()).isEqualTo(expectedContent);
DB에 저장된 데이터들을 바탕으로 검증하시는 부분 좋습니다!
하지만 데이터가 많아질 경우 `findAll()`은 너무 무거운 작업이 돼요. (지금처럼 데이터가 소량일 경우에는 큰 무리없이 작동하겠지만요) 또한 해당 코드에서 `all`의 첫 번째 원소의 값만 이용하고 있기 때문에 더더욱 `findAll()`은 불필요할 것 같습니다.

따라서 위에서 저장한 데이터만 조회하여 검증하는 로직으로 수정하시면 좋을 것 같아요!

2023-11-14 17:11 UTC, nusuy commented on server-toy-project/src/main/java/com/gdsc_teamb/servertoyproject/dto/BoardListDto.java
> +    private UserEntity user; // 작성자 정보
응답으로 UserEntity 자체를 반환하게 되면, Entity가 가진 모든 데이터를 보여주게 되므로 좋지 않습니다. 게시글도 Entity 자체가 아닌 Dto로 만들어 반환하는 것처럼 UserEntity도 필요한 데이터만 선별하여 응답으로 반환하도록 수정하면 좋을 것 같아요!
게시글 정보인 것을 고려하면 닉네임 정도 되겠네요.

이 부분도요!
https://github.com/GDSC-SWU/2023-server-toy-project-team-b/blob/e6d2d2b721a2a2bb0e759f03b786ed93b3dd9d54/server-toy-project/src/main/java/com/gdsc_teamb/servertoyproject/dto/BoardReadDto.java#L14

2023-11-14 17:45 UTC, nusuy commented
### 커밋 관련
커밋 컨벤션 처음이실텐데 잘 하셨고, 깔끔해서 너무 좋습니다👍

다만 몇 가지 말씀드리자면,
1. a8fdd75 에서 커밋을 조금 더 세분화 해야할 것 같아요. 커밋 단위가 어려우시다면 일단 하나의 기능을 기준으로 커밋해보시고, 앞으로 더 고민하시면서 최대한 적합한 커밋 단위를 찾아가시면 좋을 것 같습니다.
2. afdc615 gitignore 기능을 사용한다는 의미에서 `feat`으로 판단하신 것 같기도 합니다! 하지만 `feat`은 댓글 작성, 댓글 삭제~ 등 API의 기능을 새로 추가했을 때 사용해요. gitignore는 `chore`가 적합합니다.
3. 0be83d5 e6d2d2b 에서 주석 관련 수정사항은 `chore`가 더 적합할 듯 합니다. `docs`는 readme나 LICENSE 같은 텍스트 문서 파일 수정 시 적합한 type 같아요. 그리고 주석은 따로 작업하신 것 같은데, 가능하면 처음 기능 구현하실 때 함께 적어두시는 것을 더 권장합니다!

type이 헷갈릴 경우 깃헙 검색이나 구글링 많이 해보시면 예시가 많으니 참고하시면 좋을 것 같아요😉

2023-11-16 06:57 UTC, nanna29 commented on server-toy-project/src/main/java/com/gdsc_teamb/servertoyproject/domain/repository/BoardRepository.java
> +public interface BoardRepository extends JpaRepository<PostEntity, Long> {
수정완료했습니다!

2023-11-17 14:36 UTC, nusuy commented on server-toy-project/src/main/java/com/gdsc_teamb/servertoyproject/domain/repository/BoardRepository.java
> +public interface BoardRepository extends JpaRepository<PostEntity, Long> {
> 수정완료했습니다!

수정 완료 기준은 커밋입니다! 커밋 부탁드려요~!

2023-11-19 15:27 UTC, nanna29 commented on server-toy-project/src/main/java/com/gdsc_teamb/servertoyproject/service/BoardService.java
> +                orElseThrow(()->new IllegalArgumentException("해당 게시글이 없습니다. id="+id));
만약 에러 원인을 http응답으로 전달한다면, service 계층의 update 메서드는 리턴값이 id가 아니어도 상관없을까요?

2023-11-19 15:46 UTC, nanna29 commented on server-toy-project/src/main/java/com/gdsc_teamb/servertoyproject/service/BoardService.java
> +                orElseThrow(()->new IllegalArgumentException("해당 게시글이 없습니다. id="+id));
http응답을 전달하게 하려고 try-catch문을 구현했는데 그렇게 되면 리턴값이 ResponseEntity<Object> 으로 수정되어야 하는데 service의 update 메서드는 id를 반환해야하니 이 부분 관련은 내일 여쭤보겠습니다!

2023-11-20 17:44 UTC, nanna29 commented on server-toy-project/src/main/java/com/gdsc_teamb/servertoyproject/domain/repository/BoardRepository.java
> +    List<PostEntity> findAllDesc();
수정완료했습니다!

2023-11-20 17:44 UTC, nanna29 commented on server-toy-project/src/test/java/com/gdsc_teamb/servertoyproject/controller/BoardControllerTest.java
> +    public void Posts_등록() throws Exception{
수정완료했습니다!

2023-11-20 17:44 UTC, nanna29 commented on server-toy-project/src/test/java/com/gdsc_teamb/servertoyproject/controller/BoardControllerTest.java
> +        assertThat(responseEntity.getBody()).isGreaterThan(0L);
수정완료했습니다!

2023-11-20 17:45 UTC, nanna29 commented on server-toy-project/src/main/java/com/gdsc_teamb/servertoyproject/service/BoardService.java
> +                orElseThrow(()->new IllegalArgumentException("해당 게시글이 없습니다. id="+id));
수정완료했습니다!
다만 코드에 확신이 없어서... 한번만 확인해주시면 감사하겠습니다!!

2023-11-20 17:45 UTC, nayeong29 commented on server-toy-project/src/test/java/com/gdsc_teamb/servertoyproject/controller/BoardControllerTest.java
> +        userRepository.deleteAll();
수정완료했습니다!

2023-11-20 17:46 UTC, nanna29 commented on server-toy-project/src/test/java/com/gdsc_teamb/servertoyproject/controller/BoardControllerTest.java
> +        assertThat(all.get(0).getContent()).isEqualTo(expectedContent);
수정완료했습니다! 포스트 레포에서 특정 유저 검색해서 그 유저의 포스트만 검사하도록 로직 구현했습니다

2023-11-20 17:46 UTC, nanna29 commented on server-toy-project/src/main/java/com/gdsc_teamb/servertoyproject/dto/BoardListDto.java
> +    private UserEntity user; // 작성자 정보
수정완료했습니다!

2023-11-25 11:36 UTC, nusuy commented on server-toy-project/src/test/java/com/gdsc_teamb/servertoyproject/controller/BoardControllerTest.java
> +        userRepository.deleteAll();
https://github.com/GDSC-SWU/2023-server-toy-project-team-b/blob/d400553bbcb0111157553182828114836140949f/server-toy-project/src/test/java/com/gdsc_teamb/servertoyproject/domain/repository/PostRepositoryTest.java#L28-L32

이 부분도 수정해주세요~

2023-11-25 12:00 UTC, nusuy commented on server-toy-project/src/main/java/com/gdsc_teamb/servertoyproject/service/BoardService.java
> +                orElseThrow(()->new IllegalArgumentException("해당 게시글이 없습니다. id="+id));
https://github.com/GDSC-SWU/2023-server-toy-project-team-b/blob/d400553bbcb0111157553182828114836140949f/server-toy-project/src/main/java/com/gdsc_teamb/servertoyproject/service/BoardService.java#L53-L65

수정하신 부분이 이 부분인 것 같은데, ResponseEntity 사용하셔서 응답 body에 데이터 넣는 것과 http status 설정하신 것은 너무 잘하셨습니다! 👍
클라이언트에서 데이터를 사용하려면 json 형태로 보내줘야하는데, DTO에 데이터를 담아 body에 넣으면 스프링이 json으로 변환해서 전송해줍니다. 그래서 커스텀 응답 객체를 만들어서 필요한 데이터를 선택적으로 넣어 응답을 만들어주면 좋은데, 글로 설명 드리는 것보다 직접 코드를 보시는 것이 더 좋으니 일단 레퍼런스 남길게요. 추가 설명 필요하시면 말씀 부탁드려요!

https://velog.io/@qotndus43/%EC%8A%A4%ED%94%84%EB%A7%81-API-%EA%B3%B5%ED%86%B5-%EC%9D%91%EB%8B%B5-%ED%8F%AC%EB%A7%B7-%EA%B0%9C%EB%B0%9C%ED%95%98%EA%B8%B0

2023-11-25 12:51 UTC, nanna29 commented on server-toy-project/src/test/java/com/gdsc_teamb/servertoyproject/controller/BoardControllerTest.java
> +        userRepository.deleteAll();
완료했습니다~

2023-11-27 08:02 UTC, nusuy approved these changes

2023-11-27 08:03 UTC, merged